### ISSUE TITLE
Prepare for submission to the Awesome list

### ISSUE THREAD

**Issue by cszach** [brettz9/awesome-jsdoc#2] opened 2020-08-18 17:46 UTC
I don't know if this was your initial intent, but this list should be added to the central Awesome list [here](https://github.com/sindresorhus/awesome). This is a good way to promote the `awesome-jsdoc` list (asides from putting it in your GitHub profile README of course) (note that new lists also get featured on the [Awesome Twitter account](https://twitter.com/awesome__re) as well) :+1:.

To do's (for compliance with the guidelines stated [here](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md):
- [x] Has been around for at least 30 days.
- [ ] The default branch should be named `main`, not `master`.
- [x] Includes a succinct description of the project/theme at the top of the readme.
- [x] It's the result of hard work and the best I could possibly produce.
- [x] The repo name of your list should be in lowercase slug format: `awesome-name-of-list`.
- [x] The heading title of your list should be in title case format: `# Awesome Name of List`.
- [x] Non-generated Markdown file in a GitHub repo.
- [x] The repo should have `awesome-list` & `awesome` as GitHub topics.
- [x] Not a duplicate. Please search for existing submissions.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything.
- [x] Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs. If you really need to include such items, they should be in a separate Markdown file.
- [ ] Includes a project logo/illustration whenever possible.
- [x] Entries have a description, unless the title is descriptive enough by itself.
- [x] Includes the Awesome badge.
- [x] Has a Table of Contents section.
- [ ] Has an appropriate license.
- [x] Has contribution guidelines.
- [x] Has consistent formatting and proper spelling/grammar.
- [x] Doesn't use hard-wrapping.
- [x] Doesn't include a Travis badge.
- [x] Doesn't include an `Inspired by awesome-foo` or `Inspired by the Awesome project` kinda link at the top of the readme.
- [ ] Review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).

Seems like the list has complied with most of the requirements. Renaming the `master` branch to `main` isn't that difficult. Project logo or illustration is optional, tho I will try to make one anyway. And for the license, you should use CC0.

Once all of that is done, we are well set.

Cheers. :+1:

**Comment by brettz9** [comment] 2020-08-21 14:40
Sorry, while I like the general idea of the awesome lists, I don't like what feels like being railroaded into a single-size-fits-all approach, whether in terms of choice of license or in other areas. I believe in a tolerant ecosystem which is genuinely flexible as to diversity, intellectual as well as racial, etc., and though the initiator of the project has every right to adhere to their own standards, I don't personally care for some of these restrictions it has imposed.

And while I am absolutely in favor of rejecting all real racism and acting with sensitivity, I don't like projects being pushed toward a superficial form of political correctness, without consideration of rational, non-bigoted alternative viewpoints, and where such a narrow focus may actually end up harming the cause rather than helping it (I like the phrasing of Jordan Peterson through Bill Maher that "Political correctness is the elevation of moral posturing about sensitivity over truth".)

My primary reason for sticking to `master` over `main` is convention, so if the trend becomes widespread, I will happily switch for wider compatibility, but I don't believe in exercises which I believe are wholly wasteful given not only the very large number of repos already out there using this convention, but I also think it is harmful to mistakenly ascribe too much power to words--allowing people to become so fragile, or to treat all people as so fragile, that they think a generic word can hurt them. The word "master", whether in "master of your own destiny" does not conjure up the idea of whipping your destiny into submission. I don't believe all textbooks need to stop referring to "mastery" of skills. The list can go on and on. I don't believe in wasteful exercises like this.

There are indeed some words in language which are hurtful because of overwhelming and specific usage (though even among some of these now offensive terms, some of them weren't originally offensive, but became seen as such--for a similar process of language change, look up the term "folk etymology" to see how language has changed because of inaccurate understandings of the language), but this has not been one of them (of course, genuine slavery was/is horrific, but "master" has other meanings, the term is not limited to one race either, and we should also be capable of handling abstractions and looking to intent of language use).

I think this is an area that ought to be discussed rationally and also bring in the voices of linguists who actually bring some science to consideration of the nature of language and its supposed correctness or incorrectness, sensitivity or insensitivity. I think of the prominent linguist Steven Pinker who wrote an excellent chapter on "The Language Mavens" which speaks to the follies of prescriptivism with "correct" language. Should we ban words like "whitewash" too? Or "in the red" vs. "in the black"? The connotation of "Black-hearted" may refer to the scariness to humanity of the black night, rather than to color. We don't need to run around changing all words which we try to believe is persecuting us--it is far more important to change hearts and thinking, and yes, language if it is genuinely rude--but I don't think that is the case here.

This is a complicated discussion which really ought to be discussed in a fuller context, and needs sensitivity and nuance. But I personally don't want to give further credence to what I see as wholly unnecessary if not frivolous attention to superficial detail, and perhaps sadly giving a pretext for those who are genuinely racist to dismiss all such concerns as being frivolous and politically correct, which they are not.

While I think it is generally reasonable to err on the side of sensitivity as well as to be particularly welcoming for minorities, I also don't think a few people ought to be thought of the spokespeople for a whole race, ignoring differing opinions, including dissenting voices within a given race, and getting into debates where either a self-righteous majority or a self-righteous minority incline toward claiming moral superiority and trying to shut down all dialogue (as I've already seen occur on this same topic in another repo) rather than really reflecting on what is fair and reasonable and expressing so with frankness along with courtesy. Companies are getting on the band-wagon, but I think they'd do better to make real outreach to minorities rather than harp on language that is not actually patently offensive.

So if that means we are off the Awesome List (or even if we need to change the name), then so be it. But I may revisit if it becomes technically preferable.

Closing, though I'm open to further sincere discussion--probably better in a chat form though, as some watching the repo may not be interested in our "spam". :-)

**Closed as completed** 2020-08-21 14:45 UTC
